# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20190214_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
