# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_ref', models.CharField(max_length=50)),
                ('analysis_req', models.CharField(choices=[('1', 'Soil 1-SS Basic'), ('2', 'Soil 2-SS Dairy/Beef/Sheep/Horses'), ('3', 'Soil 3-SS Sheep/Tillage'), ('4', 'Soil 4-SS Tillage'), ('5', 'Soil 5-SS Horticulture'), ('6', 'Soil 6-SS Tillage/Grassland (S1 + Mg)'), ('7', 'Soil 7-SS Organic Matter'), ('8', 'Soil 8-SS Tillage (S6 + S7)'), ('9', 'Soil 9-SS Tillage (S4 + S7)')], default='1', max_length=1)),
                ('customer_ref', models.CharField(blank=True, max_length=50)),
                ('soil_type', models.CharField(choices=[('GW', 'Well-graded gravel, fine to coarse gravel'), ('GP', 'Poorly graded gravel'), ('GM', 'Silty gravel'), ('GC', 'Clayey gravel'), ('SW', 'Well-graded sand, fine to coarse sand'), ('SP', 'Poorly graded sand'), ('SM', 'Silty sand'), ('SC', 'Clayey sand'), ('ML', 'Silt'), ('CL', 'Clay of low plasticity, lean clay'), ('OL', 'Organic silt, organic clay'), ('MH', 'Silt of high plasticity, elastic silt'), ('CH', 'Clay of high plasticity, fat clay'), ('OH', 'Organic clay, organic silt'), ('Pt', 'Peat')], default='', max_length=1)),
                ('land_use', models.CharField(choices=[('B', 'Beef'), ('D', 'Dairy'), ('G', 'Grassland'), ('H', 'Horticulture'), ('S', 'Sheep'), ('T', 'Tillage')], default='', max_length=1)),
                ('other_comments', models.CharField(blank=True, max_length=50)),
                ('sample_condition', models.CharField(max_length=50)),
                ('sampled_date', models.DateField()),
                ('submit_date', models.DateField()),
                ('recieved_date', models.DateField()),
                ('test_strt_date', models.DateField()),
                ('test_end_date', models.DateField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Received', 'Received'), ('Testing', 'Testingd'), ('Complete', 'Complete')], default='Ordered', max_length=1)),
            ],
        ),
    ]
