# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_ref_1', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_ref_2', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_location', geoposition.fields.GeopositionField(max_length=42, null=True)),
                ('sample_address', models.CharField(blank=True, max_length=250, null=True)),
                ('sample_date', models.DateField(default=django.utils.timezone.now)),
                ('soil_type', models.CharField(choices=[('Clay - low plasticity, lean clay', 'Clay - low plasticity, lean clay'), ('Clay - high plasticity, fat clay', 'Clay - high plasticity, fat clay'), ('Clay - organic', 'Clay - organic'), ('Gravel - well-graded, fine to coarse gravel', 'Gravel - well-graded, fine to coarse gravel'), ('Gravel - poorly graded', 'Gravel - poorly graded'), ('Gravel - silty', 'Gravel - silty'), ('Gravel - clayey', 'Gravel - clayey'), ('Sand - well-graded, fine to coarse Sand', 'Sand - well-graded, fine to coarse Sand'), ('Sand - poorly graded', 'Sand - poorly graded'), ('Sand - silty', 'Sand - silty'), ('Sand - clayey', 'Sand - clayey'), ('Peat', 'Peat'), ('Silt - low plasticity, lean silt', 'Silt - low plasticity, lean silt'), ('Silt - high plasticity, fat silt', 'Silt - high plasticity, fat silt'), ('Silt - organic', 'Silt - organic')], max_length=50)),
                ('land_use', models.CharField(choices=[('Beef', 'Beef'), ('Dairy', 'Dairy'), ('Grassland', 'Grassland'), ('Horticulture', 'Horticulture'), ('Sheep', 'Sheep'), ('Tillage', 'Tillage')], max_length=50)),
                ('other_comments', models.TextField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SampleResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.DecimalField(decimal_places=2, max_digits=4)),
                ('k', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lr_ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('other_comments', models.TextField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SampleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_ref', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Ordered', 'Ordered'), ('Submitted', 'Submitted'), ('Received', 'Received'), ('Complete', 'Complete')], default='Ordered', max_length=50)),
                ('testing_required', models.CharField(choices=[('SS1', 'Soil 1 - Basic'), ('SS2', 'Soil 2 - Beef, Sheep & Horses')], max_length=50)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('tested_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recievedby', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submittedby', to=settings.AUTH_USER_MODEL)),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sampleresults',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.SampleStatus'),
        ),
        migrations.AddField(
            model_name='sampledetails',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.SampleStatus'),
        ),
    ]
