# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('sample_ref', models.CharField(max_length=50)),
                ('analysis_req', models.CharField(blank=True, choices=[('1', 'Soil 1-SS Basic'), ('2', 'Soil 2-SS Dairy/Beef/Sheep/Horses'), ('3', 'Soil 3-SS Sheep/Tillage'), ('4', 'Soil 4-SS Tillage'), ('5', 'Soil 5-SS Horticulture'), ('6', 'Soil 6-SS Tillage/Grassland (S1 + Mg)'), ('7', 'Soil 7-SS Organic Matter'), ('8', 'Soil 8-SS Tillage (S6 + S7)'), ('9', 'Soil 9-SS Tillage (S4 + S7)')], max_length=1)),
                ('customer_ref', models.CharField(blank=True, max_length=50)),
                ('soil_type', models.CharField(blank=True, choices=[('GW', 'Well-graded gravel, fine to coarse gravel'), ('GP', 'Poorly graded gravel'), ('GM', 'Silty gravel'), ('GC', 'Clayey gravel'), ('SW', 'Well-graded sand, fine to coarse sand'), ('SP', 'Poorly graded sand'), ('SM', 'Silty sand'), ('SC', 'Clayey sand'), ('ML', 'Silt'), ('CL', 'Clay of low plasticity, lean clay'), ('OL', 'Organic silt, organic clay'), ('MH', 'Silt of high plasticity, elastic silt'), ('CH', 'Clay of high plasticity, fat clay'), ('OH', 'Organic clay, organic silt'), ('Pt', 'Peat')], default='', max_length=1)),
                ('land_use', models.CharField(blank=True, choices=[('B', 'Beef'), ('D', 'Dairy'), ('G', 'Grassland'), ('H', 'Horticulture'), ('S', 'Sheep'), ('T', 'Tillage')], default='', max_length=1)),
                ('other_comments', models.CharField(blank=True, max_length=50)),
                ('sample_condition', models.CharField(blank=True, max_length=50)),
                ('sample_date', models.DateField(default=datetime.datetime(2019, 2, 15, 15, 14, 4, 136925, tzinfo=utc))),
                ('submit_date', models.DateField(blank=True)),
                ('recieved_date', models.DateField(blank=True)),
                ('test_start_date', models.DateField(blank=True)),
                ('test_end_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Received', 'Received'), ('Testing', 'Testing'), ('Complete', 'Complete')], default='Submitted', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Samples',
        ),
    ]
