# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledetails',
            name='customer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sampledetails',
            name='customer_ref_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sampledetails',
            name='customer_ref_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sampledetails',
            name='land_use',
            field=models.CharField(choices=[('Beef', 'Beef'), ('Dairy', 'Dairy'), ('Grassland', 'Grassland'), ('Horticulture', 'Horticulture'), ('Sheep', 'Sheep'), ('Tillage', 'Tillage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sampledetails',
            name='other_comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sampledetails',
            name='sample_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sampledetails',
            name='sample_location',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterField(
            model_name='sampledetails',
            name='soil_type',
            field=models.CharField(choices=[('Clay - low plasticity, lean clay', 'Clay - low plasticity, lean clay'), ('Clay - high plasticity, fat clay', 'Clay - high plasticity, fat clay'), ('Clay - organic', 'Clay - organic'), ('Gravel - well-graded, fine to coarse gravel', 'Gravel - well-graded, fine to coarse gravel'), ('Gravel - poorly graded', 'Gravel - poorly graded'), ('Gravel - silty', 'Gravel - silty'), ('Gravel - clayey', 'Gravel - clayey'), ('Sand - well-graded, fine to coarse Sand', 'Sand - well-graded, fine to coarse Sand'), ('Sand - poorly graded', 'Sand - poorly graded'), ('Sand - silty', 'Sand - silty'), ('Sand - clayey', 'Sand - clayey'), ('Peat', 'Peat'), ('Silt - low plasticity, lean silt', 'Silt - low plasticity, lean silt'), ('Silt - high plasticity, fat silt', 'Silt - high plasticity, fat silt'), ('Silt - organic', 'Silt - organic')], max_length=50),
        ),
    ]
