# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil2Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_morgan_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('k_morgan_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lr_ph_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ph_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mg_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cu_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('zn_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('er_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mn_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('organic_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
            ],
        ),
        migrations.AlterField(
            model_name='soil1results',
            name='k_morgan_result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='soil1results',
            name='lr_ph_result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='soil1results',
            name='p_morgan_result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='soil1results',
            name='ph_result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
