# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-23 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_ref_1', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_ref_2', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_location', geoposition.fields.GeopositionField(max_length=42, null=True)),
                ('sample_address', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_date', models.DateField(default=django.utils.timezone.now)),
                ('analysis_req', models.CharField(choices=[('Soil-1', 'Soil 1-SS Basic'), ('Soil-2', 'Soil 2-SS Dairy/Beef/Sheep/Horses'), ('Soil-3', 'Soil 3-SS Sheep/Tillage'), ('Soil-4', 'Soil 4-SS Tillage'), ('Soil-5', 'Soil 5-SS Horticulture'), ('Soil-6', 'Soil 6-SS Tillage/Grassland (S1 + Mg)'), ('Soil-7', 'Soil 7-SS Organic Matter'), ('Soil-8', 'Soil 8-SS Tillage (S6 + S7)'), ('Soil-9', 'Soil 9-SS Tillage (S4 + S7)')], max_length=50)),
                ('soil_type', models.CharField(blank=True, choices=[('GW', 'Well-graded gravel, fine to coarse gravel'), ('GP', 'Poorly graded gravel'), ('GM', 'Silty gravel'), ('GC', 'Clayey gravel'), ('SW', 'Well-graded sand, fine to coarse sand'), ('SP', 'Poorly graded sand'), ('SM', 'Silty sand'), ('SC', 'Clayey sand'), ('ML', 'Silt'), ('CL', 'Clay of low plasticity, lean clay'), ('OL', 'Organic silt, organic clay'), ('MH', 'Silt of high plasticity, elastic silt'), ('CH', 'Clay of high plasticity, fat clay'), ('OH', 'Organic clay, organic silt'), ('Pt', 'Peat')], default='', max_length=50)),
                ('land_use', models.CharField(blank=True, choices=[('B', 'Beef'), ('D', 'Dairy'), ('G', 'Grassland'), ('H', 'Horticulture'), ('S', 'Sheep'), ('T', 'Tillage')], default='', max_length=50)),
                ('other_comments', models.TextField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SampleResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_morgan_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('k_morgan_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lr_ph_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ph_result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lab_comments', models.TextField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SampleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_ref', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Received', 'Received'), ('Complete', 'Complete')], default='Submitted', max_length=50)),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('recieved_date', models.DateField(blank=True, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('recieved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recievedby', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittedby', to=settings.AUTH_USER_MODEL)),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sampleresults',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.SampleStatus'),
        ),
        migrations.AddField(
            model_name='sampledetails',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.SampleStatus'),
        ),
    ]
