# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplestatus',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatchedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplestatus',
            name='dispatched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplestatus',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplestatus',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplestatus',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Dispatched', 'Dispatched'), ('Submitted', 'Submitted'), ('Received', 'Received'), ('Complete', 'Complete')], default='Ordered', max_length=50),
        ),
    ]
