# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20190215_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 15, 15, 34, 59, 92351, tzinfo=utc)),
        ),
    ]
