# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-23 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20190223_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampledetails',
            name='analysis_req',
        ),
        migrations.AlterField(
            model_name='sampledetails',
            name='land_use',
            field=models.CharField(choices=[('Beef', 'Beef'), ('Dairy', 'Dairy'), ('Grassland', 'Grassland'), ('Horticulture', 'Horticulture'), ('Sheep', 'Sheep'), ('Tillage', 'Tillage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sampledetails',
            name='soil_type',
            field=models.CharField(choices=[('Clay - low plasticity, lean', 'Clay - low plasticity, lean'), ('Clay - high plasticity, fat', 'Clay - high plasticity, fat'), ('Clay - organic', 'Clay - organic'), ('Gravel - well-graded, fine to coarse gravel', 'Gravel - well-graded, fine to coarse gravel'), ('Gravel - poorly graded', 'Gravel - poorly graded'), ('Gravel - silty', 'Gravel - silty'), ('Gravel - clayey', 'Gravel - clayey'), ('Sand - well-graded, fine to coarse Sand', 'Sand - well-graded, fine to coarse Sand'), ('Sand - poorly graded', 'Sand - poorly graded'), ('Sand - silty', 'Sand - silty'), ('Sand - clayey', 'Sand - clayey'), ('Peat', 'Peat'), ('Silt - low plasticity, lean', 'Silt - low plasticity, lean'), ('Silt - high plasticity, fat', 'Silt - high plasticity, fat'), ('Silt - organic', 'Silt - organic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='samplestatus',
            name='recieved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recievedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='samplestatus',
            name='tested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
