# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-23 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20190223_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplestatus',
            old_name='recieved_by',
            new_name='received_by',
        ),
        migrations.RenameField(
            model_name='samplestatus',
            old_name='recieved_date',
            new_name='received_date',
        ),
    ]
