# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_auto_20190215_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='location',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 17, 18, 18, 45, 520793, tzinfo=utc)),
        ),
    ]
