# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-23 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20190223_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplestatus',
            old_name='test_date',
            new_name='tested_date',
        ),
        migrations.AlterField(
            model_name='samplestatus',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
