# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20190217_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='analysis_req',
            field=models.CharField(blank=True, choices=[('1', 'Soil 1-SS Basic'), ('2', 'Soil 2-SS Dairy/Beef/Sheep/Horses'), ('3', 'Soil 3-SS Sheep/Tillage'), ('4', 'Soil 4-SS Tillage'), ('5', 'Soil 5-SS Horticulture'), ('6', 'Soil 6-SS Tillage/Grassland (S1 + Mg)'), ('7', 'Soil 7-SS Organic Matter'), ('8', 'Soil 8-SS Tillage (S6 + S7)'), ('9', 'Soil 9-SS Tillage (S4 + S7)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 17, 23, 12, 0, 600065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Received', 'Received'), ('Testing', 'Testing'), ('Complete', 'Complete')], default='Submitted', max_length=50),
        ),
    ]
