# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_auto_20190217_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 17, 23, 20, 36, 281588, tzinfo=utc)),
        ),
    ]
