# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_auto_20190223_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplestatus',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplestatus',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplestatus',
            name='tested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
