# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_auto_20190217_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='site_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 18, 16, 41, 58, 241466, tzinfo=utc)),
        ),
    ]
