# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_auto_20190223_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledetails',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.SampleStatus'),
        ),
    ]
