# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_auto_20190224_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='user',
        ),
        migrations.RemoveField(
            model_name='soil1results',
            name='recieved_by',
        ),
        migrations.RemoveField(
            model_name='soil1results',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='soil2results',
            name='recieved_by',
        ),
        migrations.RemoveField(
            model_name='soil2results',
            name='sample',
        ),
        migrations.AlterField(
            model_name='sampledetails',
            name='soil_type',
            field=models.CharField(choices=[('Clay - low plasticity, lean clay', 'Clay - low plasticity, lean clay'), ('Clay - high plasticity, fat clay', 'Clay - high plasticity, fat clay'), ('Clay - organic', 'Clay - organic'), ('Gravel - well-graded, fine to coarse gravel', 'Gravel - well-graded, fine to coarse gravel'), ('Gravel - poorly graded', 'Gravel - poorly graded'), ('Gravel - silty', 'Gravel - silty'), ('Gravel - clayey', 'Gravel - clayey'), ('Sand - well-graded, fine to coarse Sand', 'Sand - well-graded, fine to coarse Sand'), ('Sand - poorly graded', 'Sand - poorly graded'), ('Sand - silty', 'Sand - silty'), ('Sand - clayey', 'Sand - clayey'), ('Peat', 'Peat'), ('Silt - low plasticity, lean silt', 'Silt - low plasticity, lean silt'), ('Silt - high plasticity, fat silt', 'Silt - high plasticity, fat silt'), ('Silt - organic', 'Silt - organic')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='Soil1Results',
        ),
        migrations.DeleteModel(
            name='Soil2Results',
        ),
    ]
