# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20190219_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='other_comments',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 19, 12, 37, 59, 596861, tzinfo=utc)),
        ),
    ]
