# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_auto_20190219_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='id',
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 19, 13, 4, 34, 677456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_ref',
            field=models.CharField(help_text='Sample reference number assigned by lab, e.g. SS-123456', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='submit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
