# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_auto_20190219_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='lab_comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
