# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_sample_lab_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Name of customer if user is ag.adviser e.g. Tom Cronin', max_length=50, null=True),
        ),
    ]
