# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_auto_20190219_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_ref',
            field=models.CharField(help_text='Sample reference number assigned by lab, e.g. SS-123456', max_length=50),
        ),
    ]
