# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190213_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='test',
            new_name='test_type',
        ),
    ]
